version: '3.1'

services:
  db:
    image: mysql:8.1.0
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: sb_tech
      MYSQL_USER: local

volumes:
  dbbase: